Repository aws-cloudformation/community-registry-extensions, pull requests merged in 2022-12, with the labels that each got.

#112 Developer Sandbox Pipeline documentation, script updates.
  RELEASE.md
  release/cicd.yml
  release/deploy-build-image.sh
  release/deploy-cicd.sh
  scripts/deploy-sandbox-pipeline.sh
Labels: documentation, ops

#110 GitHub team cicd
  release/github/cicd.yml
Labels: feature, ops

#108 GitHub webhook cicd
  release/.gitignore
  release/github/cicd.yml
Labels: feature, ops

#106 chore(release): Add GitHub Collaborator CICD
  release/github/cicd.yml
Labels: feature, ops

#107 chore(release): Move common build policy and webhooks to a common template
  release/awscommunity/cicd.yml
  release/awscommunity/release.sh
  release/common.yml
  release/deploy-cicd.sh
  release/github/cicd.yml
  release/okta/cicd.yml
  scripts/deploy-alpha.sh
  scripts/deploy-beta.sh
  scripts/deploy-prod.sh
Labels: draft, do-not-merge
