Repository aws-cloudformation/community-registry-extensions, pull requests merged in 2023-02, with the labels that each got.

#153 Update go dependencies
  resources/IAM_PasswordPolicy/go.mod
  resources/IAM_PasswordPolicy/go.sum
  resources/Time_Static/go.mod
  resources/Time_Static/go.sum
Labels: dependencies

#155 Release cfn-guard-rs-hook to v0.2.1
  packages/cfn_guard_rs_hook/cfn_guard_rs_hook/__init__.py
  packages/cfn_guard_rs_hook/cfn_guard_rs_hook/guard_hook.py
  packages/cfn_guard_rs_hook/cfn_guard_rs_hook/types.py
  packages/cfn_guard_rs_hook/poetry.lock
  packages/cfn_guard_rs_hook/pyproject.toml
Labels: ops, package

#158 Add activation instructions to S3_DeleteBucketContents
  resources/S3_DeleteBucketContents/README.md
  resources/S3_DeleteBucketContents/activation.png
Labels: documentation

#156 Update boolean tests for converting from strings
  packages/cfn_guard_rs_hook/cfn_guard_rs_hook/types.py
  packages/cfn_guard_rs_hook/poetry.lock
  packages/cfn_guard_rs_hook/pyproject.toml
  packages/cfn_guard_rs_hook/tests/helpers.py
  packages/cfn_guard_rs_hook/tests/test_cfn_guard_rs_hook.py
  packages/cfn_guard_rs_hook/tests/test_types.py
Labels: bug
