Repository aws-cloudformation/community-registry-extensions, pull requests merged in 2023-01, with the labels that each got.

#117 Fastly CICD
  release/fastly/cicd.yml
  release/fastly/release.sh
  release/webhook.py
Labels: feature, ops

#119 Use the correct type
  resources/IAM_PasswordPolicy/test/integ.yml
Labels: bug, resource

#118 Expain the use of one setup.[yml|json]
  CONTRIBUTING.md
Labels: documentation

#121 Fix okta cicd
  release/common.yml
  release/okta/cicd.yml
Labels: feature, ops

#120 Add AwsCommunity::Account::AlternateContact
  resources/Account_AlternateContact/.gitignore
  resources/Account_AlternateContact/.rpdk-config
  resources/Account_AlternateContact/README.md
  resources/Account_AlternateContact/awscommunity-account-alternatecontact.json
  resources/Account_AlternateContact/docs/README.md
  resources/Account_AlternateContact/inputs/inputs_1_create.json
  resources/Account_AlternateContact/inputs/inputs_1_invalid.json
  resources/Account_AlternateContact/inputs/inputs_1_update.json
  resources/Account_AlternateContact/requirements.txt
  resources/Account_AlternateContact/resource-role.yaml
  resources/Account_AlternateContact/src/awscommunity_account_alternatecontact/__init__.py
  resources/Account_AlternateContact/src/awscommunity_account_alternatecontact/actions.py
  resources/Account_AlternateContact/src/awscommunity_account_alternatecontact/constants.py
  resources/Account_AlternateContact/src/awscommunity_account_alternatecontact/handlers.py
  resources/Account_AlternateContact/src/awscommunity_account_alternatecontact/models.py
  resources/Account_AlternateContact/template.yml
  resources/Account_AlternateContact/test/integ.yml
  resources/Account_AlternateContact/test/setup.yml
Labels: feature, resource

#123 S3 Bucket Module
  modules/S3_Bucket/.rpdk-config
  modules/S3_Bucket/cleanup.sh
  modules/S3_Bucket/fragments/bucket.yml
  modules/S3_Bucket/schema.json
  modules/S3_Bucket/setup.sh
  modules/S3_Bucket/test/integ.yml
  modules/S3_Bucket/test/setup.yml
  modules/alpha-buildspec.yml
  release/awscommunity/cicd.yml
  release/requirements.txt
Labels: feature, module

#127 Fix okta application resource path
  release/common.yml
  release/okta/cicd.yml
Labels: bug, resource

#126 Add dependency review and python package scanning on PR
  .github/workflows/dependency.yml
  hooks/CloudFront_LoggingEnabled/requirements-dev.txt
  hooks/S3_BucketVersioningEnabled/requirements-dev.txt
  release/requirements.txt
  resources/S3_BucketNotification/requirements-dev.txt
  resources/S3_DeleteBucketContents/requirements-dev.txt
Labels: feature, dependencies

#128 Alternate contact cicd
  release/awscommunity/cicd.yml
  release/common.yml
  resources/Account_AlternateContact/src/awscommunity_account_alternatecontact/handler_test.py
Labels: feature, ops, resource
